import type { AbandonedCart, BusinessSettings, CategoryItem, Coupon, CustomerUser, Order, OrderStatus, PaymentStatus, Product, ProductReview, ReviewStatus, SavedAddress, SiteContent } from "../types";

const EMPTY_SETTINGS = {
  businessName: "HIGH STREET SOCIETY", businessPhones: ["+8801879665602", "+8801303080934"], businessEmail: "", address: "",
  instagramUrl: "https://www.instagram.com/highstreetsoociety?stkn=bGt3MmE3MTZ2ZzB1", instagramHandle: "@highstreetsoociety",
  facebookUrl: "https://www.facebook.com/profile.php?id=61583748077350", deliveryInsideDhaka: 80, deliveryOutsideDhaka: 120,
  enableBkash: true, enableNagad: true, enableCod: true, bKashMerchantNumber: "0187966502", bKashAccountType: "Personal",
  bKashAppKey: "", bKashAppSecret: "", bKashUsername: "", bKashLiveMode: false, nagadMerchantNumber: "0187966502",
  nagadAccountType: "Personal", smsGatewayProvider: "unconfigured", announcementText: "NEW DROP LIVE · NATIONWIDE DELIVERY",
  announcementActive: true, heroTitle: "HIGH STREET SOCIETY", heroSubtitle: "CONTEMPORARY STREETWEAR & EDITORIAL ART",
  heroCtaText: "SHOP THE DROP", heroImage: "/images/hss-hero-campaign.jpg", heroSize: "compact", shippingPolicy: "", returnPolicy: "",
  privacyPolicy: "", termsPolicy: "", faqList: [],
} as BusinessSettings;

const EMPTY_CONTENT = {
  homepage: { announcementText: "NEW DROP LIVE · NATIONWIDE DELIVERY", showAnnouncement: true, heroEyebrow: "HSS · EST. 2025", heroTitle: "HIGH STREET SOCIETY", heroSubtitle: "CONTEMPORARY STREETWEAR & EDITORIAL ART", heroDescription: "Premium heavyweight streetwear and archival art prints.", heroCtaText: "SHOP THE DROP", heroCtaLink: "shop", heroSecondaryCtaText: "EXPLORE POSTERS", heroSecondaryCtaLink: "posters", heroImage: "/images/hss-hero-campaign.jpg", showHero: true, newDropsEyebrow: "LATEST RELEASES", newDropsTitle: "NEW DROPS", newDropsDescription: "", showNewDrops: true, categoriesEyebrow: "DEPARTMENTS", categoriesTitle: "EXPLORE ARCHIVES", showCategories: true, editorialEyebrow: "EDITORIAL STATEMENT", editorialTitle: "CONTEMPORARY ATTITUDE.", editorialHighlight: "UNCOMPROMISING FORM.", editorialText: "", editorialBadge: "EST. 2025", editorialCtaText: "EXPLORE DROP", editorialCtaLink: "shop", showEditorial: true, featuredEyebrow: "CURATED SELECTION", featuredTitle: "FEATURED PIECES", featuredDescription: "", showFeatured: true, reviewsEyebrow: "WHAT PEOPLE ARE SAYING", reviewsTitle: "CLIENT VOICES", showReviews: true, showAssurance: true, assurancePillar1Title: "NATIONWIDE DELIVERY", assurancePillar1Text: "Express courier delivery across Bangladesh.", assurancePillar2Title: "BKASH & COD", assurancePillar2Text: "Manual payment verification and Cash on Delivery.", assurancePillar3Title: "SIZE EXCHANGE", assurancePillar3Text: "Exchange support for eligible unworn clothing.", instagramTitle: "FOLLOW THE MOVEMENT", instagramText: "Follow the official High Street Society Instagram.", instagramCtaText: "FOLLOW @highstreetsoociety", showInstagram: true, newsletterEyebrow: "THE SOCIETY CIRCLE", newsletterTitle: "JOIN HIGH STREET SOCIETY", newsletterText: "New-drop announcements.", newsletterCtaText: "JOIN THE DROP", showNewsletter: true },
  navigation: { menuHome: "HOME", menuShop: "SHOP", menuNewDrops: "NEW DROPS", menuCategories: "CATEGORIES", menuAbout: "ABOUT" },
  footer: { brandName: "HIGH STREET SOCIETY", estText: "EST. 2025", brandDescription: "Contemporary streetwear and art prints.", shopHeading: "SHOP", helpHeading: "HELP", accountHeading: "ACCOUNT", copyrightText: "© HIGH STREET SOCIETY" },
  about: { heroEyebrow: "THE SOCIETY", heroTitle: "WEAR YOUR WORLD.", heroSubtitle: "", heroImage: "/images/hss-hero-campaign.jpg", genesisHeading: "THE GENESIS", genesisPara1: "", genesisPara2: "", dualMediumHeading: "THE DUAL MEDIUM", dualMediumPara1: "", dualMediumPara2: "", starHeading: "THE SIGNATURE STAR", starText: "", starCtaText: "EXPLORE THE DROP" },
  sizeGuide: { title: "SIZE GUIDE", badge: "EST. 2025", instructions: "Measurements are in inches.", fitNote: "", careNote: "" },
  contact: { title: "CONTACT THE SOCIETY", subtitle: "CLIENT CONCIERGE", phonePrimary: "+8801879665602", phoneSecondary: "+8801303080934", email: "", location: "Dhaka, Bangladesh", formHeading: "SEND A MESSAGE", formSuccess: "Thank you. We will contact you shortly." },
  checkout: { title: "SECURE CHECKOUT", contactSectionTitle: "CONTACT & DELIVERY", deliverySectionTitle: "DELIVERY", paymentSectionTitle: "PAYMENT METHOD", summaryTitle: "ORDER SUMMARY", manualVerificationNotice: "Payment is manually verified by HSS.", bkashInstructions: "Use Send Money.", nagadInstructions: "Use Send Money.", codInstructions: "Pay upon delivery.", orderConfirmedTitle: "ORDER RECEIVED", orderConfirmedSubtitle: "THANK YOU", nextStepsMessage: "We will contact you shortly." },
  emptyStates: { emptyBagTitle: "Your bag is empty", emptyBagSubtitle: "Explore the latest drop.", emptyBagCta: "DISCOVER THE DROP", noProductsTitle: "No products found", noProductsSubtitle: "No products match this selection.", searchEmptyTitle: "No results", searchEmptySubtitle: "Try another search." },
} as SiteContent;

const cache = { products: [] as Product[], categories: [] as CategoryItem[], orders: [] as Order[], customers: [] as CustomerUser[], customer: null as CustomerUser | null, coupons: [] as Coupon[], reviews: [] as ProductReview[], notifications: [] as any[], abandoned: [] as AbandonedCart[], settings: EMPTY_SETTINGS, content: EMPTY_CONTENT, draft: EMPTY_CONTENT, analytics: { totalRevenue: 0, totalOrderCount: 0, averageOrderValue: 0, topProducts: [], sizeSalesMap: {}, colorSalesMap: {}, posterDimMap: {}, paymentBreakdown: { bkashCount: 0, bkashRevenue: 0, codCount: 0, codRevenue: 0 }, lowStockProducts: [] } as any };

async function api<T>(action: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api?action=${action}`, { credentials: "include", headers: { "content-type": "application/json" }, ...init });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || "Request failed");
  return body as T;
}

function product(raw: any): Product {
  const variants = raw.variants ?? [];
  return { ...raw, variants, category: raw.category ?? "standard", images: (raw.images ?? []).map((i: any) => typeof i === "string" ? i : i.url), clothingSizes: [...new Set(variants.map((v: any) => v.size).filter(Boolean))], clothingColors: [...new Map(variants.filter((v: any) => v.colorName).map((v: any) => [v.colorName, { name: v.colorName, hex: v.colorHex ?? "#000" }])).values()], posterDimensions: variants.filter((v: any) => v.posterSizeName).map((v: any) => ({ id: v.id, name: v.posterSizeName, width: Number(v.width), height: Number(v.height), unit: v.unit ?? "IN", price: v.price ?? raw.price, stock: v.stock, sku: v.sku })), createdAt: `${raw.createdAt}`, updatedAt: `${raw.updatedAt}` };
}

function review(raw: any): ProductReview {
  const row = raw.review ?? raw;
  return { id: row.id, productId: row.productId, productName: cache.products.find((p) => p.id === row.productId)?.name ?? "HSS Piece", customerId: row.customerId, customerName: row.customerName, rating: row.rating, comment: row.reviewText ?? row.comment, isVerifiedPurchase: row.verifiedPurchase ?? false, status: row.status, loveCount: Number(raw.loveCount ?? row.loveCount ?? 0), featuredOnHomepage: row.featuredOnHomepage, createdAt: `${row.createdAt}`, updatedAt: `${row.updatedAt}` };
}

export class DatabaseService {
  static async initialize() { const [data, session] = await Promise.all([api<any>("store"), api<any>("customer-session").catch(()=>({customer:null}))]); cache.products = (data.products ?? []).map(product); cache.categories = data.categories ?? []; cache.settings = { ...EMPTY_SETTINGS, ...(data.settings ?? {}) }; cache.content = data.cms?.site ? { ...EMPTY_CONTENT, ...data.cms.site } : EMPTY_CONTENT; cache.draft = cache.content; cache.customer=session.customer; cache.reviews=(data.reviews??[]).map((x:any)=>{const r=x.review??x;return{id:r.id,productId:r.productId,productName:cache.products.find(p=>p.id===r.productId)?.name??"HSS Piece",customerId:r.customerId,customerName:r.customerName,rating:r.rating,comment:r.reviewText??r.comment,isVerifiedPurchase:r.verifiedPurchase??false,status:r.status,loveCount:Number(x.loveCount??r.loveCount??0),featuredOnHomepage:r.featuredOnHomepage,createdAt:`${r.createdAt}`,updatedAt:`${r.updatedAt}`};}); }
  static async hydrateAdmin() { const get = (r: string) => api<any[]>(`admin-resource&resource=${r}`); const [p,c,o,u,cp,r,n,cm,a] = await Promise.all([... ["products","categories","orders","customers","coupons","reviews","notifications","cms"].map(get), api<any>("admin-dashboard")]); cache.products=p.map(product); cache.categories=c; cache.orders=o; cache.customers=u; cache.coupons=cp; cache.reviews=r.map(review); cache.notifications=n; cache.analytics=a; const site=cm.find((x:any)=>x.key==="site"); if(site){cache.content={...EMPTY_CONTENT,...site.publishedContent};cache.draft={...cache.content,...site.draftContent};} }
  static getProducts(){return cache.products;} static getProductBySlug(s:string){return cache.products.find(p=>p.slug===s||p.id===s);} static getProductById(id:string){return cache.products.find(p=>p.id===id);}
  static getCategories(all=false){return all?cache.categories:cache.categories.filter(c=>c.isActive!==false);} static getCategoryBySlug(s:string){return cache.categories.find(c=>c.slug===s||c.id===s);} static getCategoryProductCount(s:string){return cache.products.filter(p=>p.category===s).length;}
  static getSettings(){return cache.settings;} static getSiteContent(_preview=false){return cache.content;} static getDraftSiteContent(){return cache.draft;} static getOrders(){return cache.orders;} static getOrderById(id:string){return cache.orders.find(o=>o.id===id||(o as any).orderNumber===id);} static getCustomers(){return cache.customers;} static getCoupons(){return cache.coupons;} static getReviews(id?:string,all=false){return cache.reviews.filter(r=>(!id||r.productId===id)&&(all||r.status==="approved"));} static getHomepageFeaturedReviews(){return cache.reviews.filter(r=>r.status==="approved"&&r.featuredOnHomepage);} static getAdminNotifications(){return cache.notifications;} static getAbandonedCarts(){return cache.abandoned;} static getActiveSession():CustomerUser|null{return cache.customer;} static getWishlist(){return cache.customer?.wishlist??[];} static isReviewLovedByMe(_id?:string){return false;}
  static saveDraftSiteContent(c:SiteContent){cache.draft=c;void api("admin-cms",{method:"POST",body:JSON.stringify({key:"site",content:c,publish:false})});return c;} static publishSiteContent(c:SiteContent){cache.content=c;cache.draft=c;void api("admin-cms",{method:"POST",body:JSON.stringify({key:"site",content:c,publish:true})});return c;} static resetSiteContentToDefault(){cache.content=EMPTY_CONTENT;cache.draft=EMPTY_CONTENT;return EMPTY_CONTENT;}
  static async saveProduct(p:any){
    const category=cache.categories.find(c=>c.slug===p.category);
    if(!category) throw new Error("Select a valid category");
    const productPayload={id:p.id,categoryId:category.id,name:p.name,slug:p.slug,tagline:p.tagline??"",description:p.description??"",details:p.details??[],fabric:p.fabric,sku:p.sku,price:Number(p.price),compareAtPrice:p.compareAtPrice?Number(p.compareAtPrice):null,stock:Number(p.stock??0),isNewDrop:Boolean(p.isNewDrop),isFeatured:Boolean(p.isFeatured),isPublished:p.isPublished!==false};
    const externalImages=(p.images??[]).filter((url:string)=>!url.startsWith("data:image/")).map((url:string,index:number)=>({url,altText:p.name,sortOrder:index,isPrimary:index===0}));
    let variants:any[]=[];
    if(category.variantType==="posters")variants=(p.posterDimensions??[]).map((v:any)=>({sku:v.sku||`${p.sku}-${v.name}`,posterSizeName:v.name,width:String(v.width),height:String(v.height),unit:v.unit||"IN",price:Number(v.price),stock:Number(v.stock),reservedStock:0,isActive:true}));
    if(category.variantType==="clothing")variants=(p.clothingSizes??[]).flatMap((size:string)=>(p.clothingColors?.length?p.clothingColors:[{name:"Default",hex:"#000000"}]).map((color:any)=>({sku:`${p.sku}-${size}-${color.name}`.replace(/\s+/g,"-").toUpperCase(),size,colorName:color.name,colorHex:color.hex,price:Number(p.price),stock:Number(p.stock),reservedStock:0,isActive:true})));
    const saved=await api<any>("admin-product-save",{method:"POST",body:JSON.stringify({product:productPayload,images:externalImages,variants})});
    const uploaded=[] as any[];
    for(const dataUri of (p.images??[]).filter((url:string)=>url.startsWith("data:image/"))){const image=await api<any>("admin-image-upload",{method:"POST",body:JSON.stringify({productId:saved.id,dataUri})});uploaded.push({url:image.url,publicId:image.publicId,altText:p.name,sortOrder:externalImages.length+uploaded.length,isPrimary:externalImages.length===0&&uploaded.length===0});}
    if(uploaded.length)await api("admin-product-save",{method:"POST",body:JSON.stringify({product:{...productPayload,id:saved.id},images:[...externalImages,...uploaded],variants})});
    return saved as Product;
  } static deleteProduct(id:string){void api(`admin-product-delete&id=${id}`,{method:"DELETE"});return true;} static duplicateProduct(id:string){const p=cache.products.find(x=>x.id===id);if(p)void this.saveProduct({...p,id:undefined,slug:`${p.slug}-copy`,sku:`${p.sku}-COPY`});return p??null;} static updateProductStock(id:string,stock:number){void api("admin-inventory",{method:"PATCH",body:JSON.stringify({variantId:id,stock})});return true;} static bulkUpdateProducts(ids:string[],u:Partial<Product>){ids.forEach(id=>{const p=cache.products.find(x=>x.id===id);if(p)void this.saveProduct({...p,...u});});} static bulkDeleteProducts(ids:string[]){ids.forEach(id=>this.deleteProduct(id));}
  static saveCategory(c:any){void api("admin-category-save",{method:"POST",body:JSON.stringify(c)});return c as CategoryItem;} static toggleCategoryActive(id:string){const c=cache.categories.find(x=>x.id===id);if(c)void this.saveCategory({...c,isActive:!c.isActive});return true;} static reorderCategories(ids:string[]){ids.forEach((id,i)=>{const c=cache.categories.find(x=>x.id===id);if(c)void this.saveCategory({...c,sortOrder:i+1});});return true;} static deleteCategory(id:string):{success:boolean;error?:string}{void api(`admin-category-delete&id=${id}`,{method:"DELETE"});return{success:true};}
  static validateCoupon(code:string,_subtotal?:number,_identity?:string){const c=cache.coupons.find(x=>x.code.toUpperCase()===code.toUpperCase());return{valid:false,discount:0,coupon:c,error:"Coupon validation requires the server"};} static async validateCouponServer(code:string,phone:string|undefined,items:any[]){return api<any>("coupon-validate",{method:"POST",body:JSON.stringify({code,phone,items})});} static saveCoupon(c:any){void api("admin-coupon-save",{method:"POST",body:JSON.stringify(c)});return c as Coupon;} static deleteCoupon(id:string){void api(`admin-coupon-delete&id=${id}`,{method:"DELETE"});return true;}
  static async createOrder(p:any){try{const {paymentReferenceId,...rest}=p;const order=await api<any>("order-create",{method:"POST",body:JSON.stringify({...rest,transactionId:paymentReferenceId,idempotencyKey:crypto.randomUUID()})});cache.orders.unshift(order);return{success:true,order};}catch(e){return{success:false,error:e instanceof Error?e.message:"Order failed"};}} static async trackOrder(n:string,phone:string){try{return await api<Order>(`order-track&orderNumber=${encodeURIComponent(n)}&phone=${encodeURIComponent(phone)}`);}catch{return undefined;}} static updateOrderStatus(id:string,status:OrderStatus,_note?:string){void api("admin-order-status",{method:"PATCH",body:JSON.stringify({orderId:id,status})});return true;} static updateOrderPaymentStatus(_id:string,_s:PaymentStatus){return false;} static updateOrderCourier(_id:string,_courier:string,_tracking:string,_url?:string){return false;} static verifyPayment(id:string,_a:string,note:string){void api("admin-payment-verify",{method:"POST",body:JSON.stringify({orderId:id,approved:true,note})});return{success:true,order:this.getOrderById(id)};} static rejectPayment(id:string,_a:string,note:string){void api("admin-payment-verify",{method:"POST",body:JSON.stringify({orderId:id,approved:false,note})});return{success:true,order:this.getOrderById(id)};}
  static async submitReview(p:any){try{const review=await api<ProductReview>("review-create",{method:"POST",body:JSON.stringify({productId:p.productId,customerName:p.customerName,rating:p.rating,reviewText:p.comment,phone:p.customerPhone})});cache.reviews.unshift(review);return{success:true,review};}catch(e){return{success:false,error:e instanceof Error?e.message:"Review failed"};}} static async toggleReviewLove(id:string){return api("review-react",{method:"POST",body:JSON.stringify({reviewId:id})});} static updateReviewStatus(id:string,status:ReviewStatus){void api("admin-review",{method:"PATCH",body:JSON.stringify({id,status})});return true;} static toggleReviewHomepage(id:string){const r=cache.reviews.find(x=>x.id===id);void api("admin-review",{method:"PATCH",body:JSON.stringify({id,featuredOnHomepage:!r?.featuredOnHomepage})});return true;} static deleteReview(_id?:string){return false;}
  static async toggleWishlist(id:string){try{await api("customer-wishlist",{method:"POST",body:JSON.stringify({productId:id})});const s=await api<any>("customer-session");cache.customer=s.customer;return cache.customer?.wishlist??[];}catch{return cache.customer?.wishlist??[];}} static async customerLogin(identity:string,password:string){try{const r=await api<any>("customer-login",{method:"POST",body:JSON.stringify({identity,password})});cache.customer=r.customer;return{success:true,user:r.customer as CustomerUser};}catch(e){return{success:false,error:e instanceof Error?e.message:"Login failed"};}} static async customerRegister(payload:any){try{const r=await api<any>("customer-register",{method:"POST",body:JSON.stringify(payload)});cache.customer=r.customer;return{success:true,user:r.customer as CustomerUser};}catch(e){return{success:false,error:e instanceof Error?e.message:"Registration failed"};}} static async customerLogout(){await api("customer-logout",{method:"POST",body:"{}"}).catch(()=>undefined);cache.customer=null;} static updateCustomerProfile(_id?:string,_update?:Partial<CustomerUser>){return null;} static async saveCustomerAddress(_id:string,address:Omit<SavedAddress,"id">){await api("customer-address",{method:"POST",body:JSON.stringify({label:address.label,recipientName:address.fullName,phone:address.phone,district:address.district,area:address.area,address:address.address,deliveryLocation:address.deliveryLocation,isDefault:address.isDefault})});const s=await api<any>("customer-session");cache.customer=s.customer;return cache.customer?.savedAddresses??[];} static trackAbandonedCart(c:AbandonedCart){void api("abandoned-cart",{method:"POST",body:JSON.stringify(c)}).catch(()=>undefined);}
  static saveSettings(s:Partial<BusinessSettings>){cache.settings={...cache.settings,...s};Object.entries(s).forEach(([key,value])=>void api("admin-setting",{method:"POST",body:JSON.stringify({key,value})}));return cache.settings;} static addSubscriber(email:string){void api("newsletter",{method:"POST",body:JSON.stringify({email})});return{success:true,message:"Subscription received."};} static getSubscribers(){return [];} static markAllAdminNotificationsRead(){} static markAdminNotificationRead(_id:string){} static getAnalytics(_range?:string):any{return cache.analytics;} static exportDatabase(){return JSON.stringify({error:"Use PostgreSQL backups"});} static importDatabase(_json?:string):{success:boolean;error?:string}{return{success:false,error:"Use server migrations"};}
}