#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Bring up the local Afif OS stack from nothing.
#
# Written because the sandbox this project is developed in discards
# node_modules, .next, .env.local and everything under /tmp between sessions,
# so the environment has to be rebuilt from scratch repeatedly. Every step here
# is idempotent: anything already present is left alone.
#
# Usage:  bash scripts/dev-up.sh
#
# It does NOT start the Next.js server — run `npm start` (or `npm run dev`)
# afterwards, so the server can be supervised separately.
# ---------------------------------------------------------------------------
set -euo pipefail

cd "$(dirname "$0")/.."

PG_VERSION_DIR="/tmp/pglocal"
PGDATA="/tmp/pgdata"
PGPORT="${PGPORT:-5433}"
PGBIN="$PG_VERSION_DIR/node_modules/@embedded-postgres/linux-x64/native/bin"

say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

# --- 1. Node dependencies -------------------------------------------------
if [ -d node_modules/next ]; then
  say "node_modules present — skipping npm ci"
else
  say "Installing node dependencies"
  npm ci --no-audit --no-fund
fi

# --- 2. Embedded PostgreSQL binaries --------------------------------------
# There is no system PostgreSQL package available here, so use the npm
# embedded build. Kept under /tmp because it is a large platform binary that
# should not live in the repository.
if [ -x "$PGBIN/pg_ctl" ]; then
  say "PostgreSQL binaries present — skipping install"
else
  say "Installing embedded PostgreSQL"
  mkdir -p "$PG_VERSION_DIR"
  ( cd "$PG_VERSION_DIR" \
    && echo '{"name":"pglocal","private":true}' > package.json \
    && npm install @embedded-postgres/linux-x64 --no-audit --no-fund )
fi

# --- 3. Data directory ----------------------------------------------------
if [ -d "$PGDATA/base" ]; then
  say "Data directory present — skipping initdb"
else
  say "Initialising the database cluster"
  "$PGBIN/initdb" -D "$PGDATA" -U postgres --auth=trust -E UTF8 > /dev/null
fi

# --- 4. Server ------------------------------------------------------------
if ss -lptnH "sport = :$PGPORT" 2>/dev/null | grep -q .; then
  say "PostgreSQL already listening on $PGPORT"
else
  say "Starting PostgreSQL on $PGPORT"
  "$PGBIN/pg_ctl" -D "$PGDATA" \
    -o "-p $PGPORT -k /tmp -c listen_addresses=127.0.0.1" \
    -l /tmp/pg.log start
  for _ in $(seq 1 30); do
    ss -lptnH "sport = :$PGPORT" 2>/dev/null | grep -q . && break
    sleep 1
  done
fi

# --- 5. .env.local --------------------------------------------------------
# Never committed. Generated with fresh secrets when absent. COOKIE_SAMESITE
# and SERVER_ACTION_ALLOWED_ORIGINS are what make login work when the app is
# embedded in a cross-site iframe behind a TLS-terminating proxy — see
# .env.example for the full reasoning.
if [ -f .env.local ]; then
  say ".env.local present — leaving it untouched"
else
  say "Writing .env.local with generated secrets"
  AUTH_SECRET="$(node -e 'console.log(require("node:crypto").randomBytes(32).toString("hex"))')"
  TICK_TOKEN="$(node -e 'console.log(require("node:crypto").randomBytes(24).toString("hex"))')"
  cat > .env.local <<EOF
# Generated by scripts/dev-up.sh — local development only, never committed.

DATABASE_URL="postgres://postgres@127.0.0.1:$PGPORT/afif_os"
AUTH_SECRET="$AUTH_SECRET"
SESSION_COOKIE="afif_os_session"
SESSION_TTL_HOURS="12"
NODE_ENV="development"
DEFAULT_TIMEZONE="Asia/Dhaka"
ALLOW_FIRST_USER_SETUP="1"
REMINDER_TICK_TOKEN="$TICK_TOKEN"

# Required when the app is embedded in a cross-site iframe behind a proxy that
# terminates TLS: SameSite=Lax would be stored by the browser and then never
# sent, and Next would abort every Server Action on an Origin mismatch.
COOKIE_SAMESITE="none"
SERVER_ACTION_ALLOWED_ORIGINS="*.e2b.app,localhost,127.0.0.1"
EOF
fi

# --- 6. Database, migrations, seed ---------------------------------------
say "Creating the database if needed"
PGPORT="$PGPORT" node --conditions=react-server --import tsx - <<'EOF'
import postgres from "postgres";
const port = process.env.PGPORT ?? "5433";
const admin = postgres(`postgres://postgres@127.0.0.1:${port}/postgres`, { max: 1 });
const rows = await admin.unsafe(`SELECT 1 FROM pg_database WHERE datname = 'afif_os'`);
if (rows.length === 0) {
  await admin.unsafe(`CREATE DATABASE afif_os`);
  console.log("created database afif_os");
} else {
  console.log("database afif_os already exists");
}
await admin.end({ timeout: 5 });
process.exit(0);
EOF

say "Applying migrations"
npm run db:migrate

say "Seeding (idempotent — safe to re-run)"
npm run db:seed -- --confirm

# --- 7. Build -------------------------------------------------------------
if [ -d .next/BUILD_ID ]; then
  say "Build present — skipping next build"
else
  say "Building"
  npm run build
fi

say "Ready. Start the server with: npm start"
